namespace Senlin.Mo.Localization.Abstractions;

/// <summary>
/// Localization string
/// </summary>
/// <param name="value">the key of json(auto generated by json)</param>
/// <param name="args">the args of json value</param>
public struct LocalizationString(string value, params string[] args)
{
    private bool _isResolved;

    /// <summary>
    /// Get the final string by resolve function
    /// </summary>
    /// <param name="resolve"></param>
    /// <returns></returns>
    public string Resolve(LocalizationStringResolve resolve)
    {
        if (_isResolved)
        {
            return value;
        }

        _isResolved = true;
        return value = resolve(value, args);
    }
}