namespace Senlin.Mo.Localization.Abstractions;

/// <summary>
/// Localization string
/// </summary>
/// <param name="key">the key of json(auto generated by json)</param>
/// <param name="args">the args of json value</param>
public struct LString(string key, params KeyValuePair<string, string>[] args)
{
    private string? _value = null;

    /// <summary>
    /// Get the final string by resolve function
    /// </summary>
    /// <param name="resolve"></param>
    /// <returns></returns>
    public string Resolve(Func<string, string> resolve)
    {
        if (_value != null)
        {
            return _value;
        }

        var s = resolve(key);
        foreach (var arg in args)
        {
            var argKey = arg.Key;
            s = s.Replace($"{{{argKey}}}", arg.Value);
        }

        return _value = s;
    }
}